### ISSUE TITLE
Creation visual alignment

### ISSUE THREAD

**Issue by alancolant** [outl1ne/nova-multiselect-field#150]
In Laravel Nova 4,
When I define the field 'singleSelect'.
The clickable button is aligned to the right in the creation tab.

![Capture d’écran de 2022-05-02 21-42-37](https://user-images.githubusercontent.com/19172637/166314481-c3c28d31-3fba-4dea-ae57-eb6efebd19a9.png)

The field is defined by:
```php
  Multiselect::make(__('City'), 'city')
                ->belongsTo(City::class)
                ->singleSelect()
                ->onlyOnForms(),
```
To fix problem, I override .multiselect class:
```css
.multiselect {
    position: relative;
    margin: 0 auto;
    width: 100%;
    display: flex; /*Remove or set block*/
    align-items: center;  /*Remove*/
    justify-content: flex-end;  /*Remove*/
    box-sizing: border-box;
    cursor: pointer;
    outline: none;
    border: var(--ms-border-width,1px) solid var(--ms-border-color,#d1d5db);
    border-radius: var(--ms-radius,4px);
    background: var(--ms-bg,#fff);
    font-size: var(--ms-font-size,1rem);
    min-height: calc(var(--ms-border-width, 1px)*2 + var(--ms-font-size, 1rem)*var(--ms-line-height, 1.375) + var(--ms-py, .5rem)*2);
}
```

I'm not sure this won't impact the visual in its "multiple" mode. But it can be a quick fix.

**Comment by stonkeep** [comment]
> In Laravel Nova 4, When I define the field 'singleSelect'. The clickable button is aligned to the right in the creation tab.
> 
> ![Capture d’écran de 2022-05-02 21-42-37](https://user-images.githubusercontent.com/19172637/166314481-c3c28d31-3fba-4dea-ae57-eb6efebd19a9.png)
> 
> The field is defined by:
> 
> ```
>   Multiselect::make(__('City'), 'city')
>                 ->belongsTo(City::class)
>                 ->singleSelect()
>                 ->onlyOnForms(),
> ```
> 
> To fix problem, I override .multiselect class:
> 
> ```css
> .multiselect {
>     position: relative;
>     margin: 0 auto;
>     width: 100%;
>     display: flex; /*Remove or set block*/
>     align-items: center;  /*Remove*/
>     justify-content: flex-end;  /*Remove*/
>     box-sizing: border-box;
>     cursor: pointer;
>     outline: none;
>     border: var(--ms-border-width,1px) solid var(--ms-border-color,#d1d5db);
>     border-radius: var(--ms-radius,4px);
>     background: var(--ms-bg,#fff);
>     font-size: var(--ms-font-size,1rem);
>     min-height: calc(var(--ms-border-width, 1px)*2 + var(--ms-font-size, 1rem)*var(--ms-line-height, 1.375) + var(--ms-py, .5rem)*2);
> }
> ```
> 
> I'm not sure this won't impact the visual in its "multiple" mode. But it can be a quick fix.

Same error here, but to multiselect
Where did you replaced the css?

**Comment by Tarpsvo** [comment]
That's really weird. I can't reproduce this issue. What version of Nova are you using, as well as what browser? Are there any other styles that are conflicting?

**Comment by stonkeep** [comment]
Difficultly. It may be that it conflicts with the css of laravel Nova itself 
You could use a prefix in your css. 
like 'outline-multiselect.' 
Sounds good?

**Comment by alancolant** [comment]
The problem still exists.
Currently i am using nova v4.6.1,
To fix some disagreements, I added custom css rules with provider.

In NovaServiceProvider.php
```php
 public function boot(){
    ...
    Nova::serving(function (ServingNova $event) {
        Nova::style('fix', __DIR__ . '/../../resources/css/fixnova.css');
    });
    ...
}
```

Then in `resources/css/fixnova.css`
```css
.multiselect {
    border: none !important;
    background: transparent !important;
}

.multiselect__tags {
    min-width: 100%;
}

/*The styles below are only used to make the select more readable in dark mode/
.multiselect__option.multiselect__option--highlight.multiselect__option--selected {
    background-color: #f87171 !important;
}

html.dark .multiselect__option.multiselect__option--highlight.multiselect__option--selected {
    background-color: #7f1d1d !important;
    color: black !important;
}
```

Since I don't have a license for nova 3, I can't check if these changes have an impact on this version.
