### ISSUE TITLE
Field UI problems

### ISSUE THREAD

**Issue by trippo** [outl1ne/nova-multiselect-field#167]
- input sty on right => .multiselect__tags need `flex-grow:1;`
- border color need to be equal to nova input color
```css
.input-class{
  border-color: rgba(var(--colors-gray-300),var(--tw-border-opacity));
}

.dark .input-class{
  border-color: rgba(var(--colors-gray-700),var(--tw-border-opacity));
}
```
<img width="622" alt="image" src="https://user-images.githubusercontent.com/497169/179347392-15dae172-f6a6-45e2-bb5e-bc51e43e3911.png">
<img width="619" alt="image" src="https://user-images.githubusercontent.com/497169/179347405-e0cebe91-9087-4de4-b383-945755f72a44.png">
